### PR TITLE
Fix identifier parsing and improve FROM clause parsing

### LINKED ISSUE #3351: [bug] EntityFrameworkCore Instrumentation hangs when tracing certain queries with umlaut in the variable names
### Component

OpenTelemetry.Instrumentation.EntityFrameworkCore

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                         | 1.13.1   |
| OpenTelemetry.Exporters.Console       | 1.13.1   |
| OpenTelemetry.Instrumentation.EntityFrameworkCore | 1.13.0-beta.1   |

### Runtime Version

net8.0

### Description

Certain queries with German umlaut like ä, ö, ü in the variable name(s) used in the query cause the tracing to hang (before exporting trace data). 

The problem only exists with the above mentioned version of `OpenTelemetry.Instrumentation.EntityFrameworkCore  1.13.0-beta.1`.
The previous version `1.12.0-beta.2` works fine.

Example of a query where tracing hangs:

```csharp
var geräteIds = new List<long>() { 1, 2, 3 };
var x = db.Tests.AsNoTracking().Where(g => geräteIds.Contains(g.Id));
```

Example of the query string of that query:

```sql
DECLARE @__geräteIds_0 nvarchar(4000) = N'[1,2,3]';

SELECT [t].[Id]
FROM [Tests] AS [t]
WHERE [t].[Id] IN (
    SELECT [g].[value]
    FROM OPENJSON(@__geräteIds_0) WITH ([value] bigint '$') AS [g]
)
```

### Steps to Reproduce

- Have a Microsoft SQL Server 2022 instance with a db `tests` and its connection string ready
- have a table `Tests` with a primary key column ID (bigint)
- the collation of the db tested was `Latin1_General_CI_AS` but it does not seem to make a difference
- create a console application
- install the above mentioned nuget packages
- fill in your actual connection string
- run the application

```csharp
using Microsoft.EntityFrameworkCore;
using OpenTelemetry;
using OpenTelemetry.Trace;

using var tracerProvider = Sdk.CreateTracerProviderBuilder()
   .AddEntityFrameworkCoreInstrumentation()
   .AddConsoleExporter()
   .Build();

using var db = new UmlautDbContext();

var geräteIds = new List<long>() { 1, 2, 3 };
var x = db.Tests.AsNoTracking().Where(g => geräteIds.Contains(g.Id));

Console.WriteLine(x.ToQueryString()); // does not influence the result whether it hangs or not

foreach (var item in x) // hangs here
{
    Console.WriteLine(item.Id);
}

public class TestEntity
{
    public long Id { get; set; }
}

public class UmlautDbContext : DbContext
{
    public DbSet<TestEntity> Tests { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder options) => options.UseSqlServer("Server=...;");
}
```

Docker compose for the required SQL Server

```yaml
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ProvideASecurePasswordHere!
      - MSSQL_COLLATION=Latin1_General_CI_AS
```

### Expected Result

It should print the existing item in the Tests table (if any) and not hang.

### Actual Result

It hangs as soon as data is accessed.

### Additional Context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by stevejgordon**
Fixes #3351

## Changes

Primarily this fixes #3351 by ensuring we check all valid letters when parsing identifiers.

Also adds support for delimited table identifiers.

This also makes the handling of comma separated tables more robust by tracking the exit of a FROM clause.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [x] Unit tests added/updated
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] ~Changes in public API reviewed (if applicable)~

### CODE REVIEW

File: src/Shared/SqlProcessor.cs [hunk 1]
```diff
@@ -35,6 +36,12 @@ internal static class SqlProcessor
     private static readonly SearchValues<char> WhitespaceSearchValues = SearchValues.Create(WhitespaceChars);
 #endif
 
+    // This is not an exhaustive list but covers the majority of common reserved SQL keywords that may follow a FROM clause.
+    // This is used when determining if the previous token is a keyword in order to identify the end of a comma separated FROM clause.
+    private static readonly string[] FromClauseReservedKeywords = [
+        "AS", "JOIN", "CROSS", "WHERE", "BY", "HAVING", "WINDOW", "LIMIT", "OFFSET", "TABLESAMPLE", "WITH", "PIVOT", "UNPIVOT"
```
Comment (martincostello) [inline src/Shared/SqlProcessor.cs]: Nit: can we sort these? Makes it easier to see if something needs adding/is missing in the future.

File: src/Shared/SqlProcessor.cs [hunk 2]
```diff
@@ -401,14 +409,42 @@ private static void ParseNextToken(
...
+                                    break;
+                                }
+                            }
+
+                            if (isMatch)
+                            {
+                                state.InFromClause = false;
+                            }
+                        }
+                    }
```
Comment (martincostello) [inline src/Shared/SqlProcessor.cs:427]: For .NET 10, we could do this with `SearchValues<T>`, right?

File: test/OpenTelemetry.Contrib.Shared.Tests/SqlProcessorAdditionalTestCases.json [hunk 3]
```diff
@@ -857,5 +857,31 @@
       ],
       "db.query.summary": "ALTER TABLE MyTable"
     }
+  },
+  {
+    "name": "query_with_german_characters",
```
Comment (martincostello) [inline test/OpenTelemetry.Contrib.Shared.Tests/SqlProcessorAdditionalTestCases.json]:
```suggestion
    "name": "query_with_diacritic_characters",
```

File: src/Shared/SqlProcessor.cs (hunk 1 above)
Comment (stevejgordon) [reply src/Shared/SqlProcessor.cs]: I've sorted in order of most likely to appear next after `FROM` to subtly optimise the lookup.

File: src/Shared/SqlProcessor.cs (hunk 2 above)
Comment (stevejgordon) [reply src/Shared/SqlProcessor.cs:427]: Yeah we probably can. It would be a micro optimisation for this case. I can either do that in a follow up PR (so as to get the main bug fix out sooner) or some time next week I can update it in this PR.

File: src/Shared/SqlProcessor.cs (hunk 1 above)
Comment (martincostello) [reply src/Shared/SqlProcessor.cs]: OK, in that case can you just add a comment to that effect?

File: src/Shared/SqlProcessor.cs (hunk 2 above)
Comment (martincostello) [reply src/Shared/SqlProcessor.cs:427]: Later is fine, as #2822 hasn't been merged yet anyway.

I thought I'd just mention it in case you'd rework this in any way to make that easier later, and I think the code would be easier to read (e.g. not needing to understand `0x20` is being used to make it case insensitive).

File: src/Shared/SqlProcessor.cs (hunk 1 above)
Comment (stevejgordon) [reply src/Shared/SqlProcessor.cs]: I've added a comment.

File: src/Shared/SqlProcessor.cs (hunk 2 above)
Comment (stevejgordon) [reply src/Shared/SqlProcessor.cs:427]: I've refactored slightly to make this code a little more self descriptive.

File: src/Shared/SqlProcessor.cs [hunk 4]
```diff
@@ -469,6 +459,27 @@ private static void ParseNextToken(
...
+            for (var charPos = 0; charPos < tokenSpan.Length; charPos++)
+            {
+                if ((tokenSpan[charPos] | 0x20) != (reservedKeywordSpan[charPos] | 0x20))
+                {
+                    isMatch = false;
+                    break;
+                }
+            }
+
+            return isMatch;
```
Comment (martincostello) [inline src/Shared/SqlProcessor.cs]: Would it make any difference to just `return false` instead of assign to `isMatch`, and just `return true` at the end?

**Review by martincostello — APPROVED** [review]

File: src/Shared/SqlProcessor.cs (hunk 4 above)
Comment (stevejgordon) [reply src/Shared/SqlProcessor.cs]: Yes it would, I've updated.

**Comment by martincostello** [comment]
@stevejgordon Would you mind adding a CHANGELOG entry for both EFCore and SqlClient for the bug fix please?

**Comment by stevejgordon** [comment]
> Would you mind adding a CHANGELOG entry for both EFCore and SqlClient for the bug fix please?

Done!
